### ISSUE TITLE
Buffer tube grip; milspec or commercial?

### ISSUE THREAD

**Issue by rlyehfhtagn** [nguyenkvvn/HeritageRoughRider-VinhsFunMods#1]
Just want to make sure I get the right size buffer tube.

**Comment by nguyenkvvn** [comment]
The buffer tube threading is mil-spec. AFAIK the com/mil spec buffer tubes only applies to the interface to the stock/brace piece, rather than the threading that would be on the lower itself.

Regardless, no one on this green earth should be using com-spec. I would be hard-pressed to find anything made for com-spec that can be printed.

**Comment by rlyehfhtagn** [comment]
Cool beans, thanks a bunch!
